openapi: 3.1.0
info:
  version: 1.0.0
  title: Your Application Name
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Your application description
tags:
  - name: Contacts
servers:
  - url: http://localhost:3000
  - url: https://deployed-site.com
paths:
  /contacts/{contactId}:
    get:
      $ref: './swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: './swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: './swagger/paths/contacts/{id}/delete.yaml'
  /contacts:
    get:
      $ref: './swagger/paths/get.yaml'
    post:
      $ref: './swagger/paths/contacts/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: './swagger/components/schemas/contactSchema.yaml'
  responses:
    ContactResponse:
      $ref: './swagger/components/responses/contactResponse.yaml'
